// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Список задач
//
//	Демонстрационное API сервиса 'список задач'
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api
//	Version: 0.1.2
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
