// Code generated by MockGen. DO NOT EDIT.
// Source: main.go

// Package main is a generated GoMock package.
package main

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAreaCalculator is a mock of AreaCalculator interface.
type MockAreaCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockAreaCalculatorMockRecorder
}

// MockAreaCalculatorMockRecorder is the mock recorder for MockAreaCalculator.
type MockAreaCalculatorMockRecorder struct {
	mock *MockAreaCalculator
}

// NewMockAreaCalculator creates a new mock instance.
func NewMockAreaCalculator(ctrl *gomock.Controller) *MockAreaCalculator {
	mock := &MockAreaCalculator{ctrl: ctrl}
	mock.recorder = &MockAreaCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAreaCalculator) EXPECT() *MockAreaCalculatorMockRecorder {
	return m.recorder
}

// GetArea mocks base method.
func (m *MockAreaCalculator) GetArea() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArea")
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetArea indicates an expected call of GetArea.
func (mr *MockAreaCalculatorMockRecorder) GetArea() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArea", reflect.TypeOf((*MockAreaCalculator)(nil).GetArea))
}
